### ISSUE TITLE
[BUG] Can't proccess elements in frames 

### ISSUE THREAD

**Issue by aaronpeng2020** [kaliiiiiiiiii/undetected-playwright-python#10]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```python
from undetected_playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()

    await page.goto("https://iframe.arkoselabs.com/2CB16598-CB82-4CF7-B332-5990DB66F3AB/index.html?mkt=en")
    await page.wait_for_load_state("networkidle")
    for frame in page.frames:
        start = await frame.query_selector('//*[@id="root"]/div/div[1]/button')
        if start:
          await start.click()

    browser.close()
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

Traceback (most recent call last):
  File "d:\dev\test\service\pass_base.py", line 188, in <module>
    loop.run_until_complete(main(data))
  File "C:\Users\8\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "d:\dev\test\service\pass_base.py", line 165, in main
    result = await run(data)
  File "d:\dev\test\service\pass_base.py", line 63, in run
    await start.click()
  File "d:\dev\test\venv\lib\site-packages\undetected_playwright\async_api\_generated.py", line 2100, in click
    await self._impl_obj.click(
  File "d:\dev\test\venv\lib\site-packages\undetected_playwright\_impl\_element_handle.py", line 137, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "d:\dev\test\venv\lib\site-packages\undetected_playwright\_impl\_connection.py", line 63, in send
    return await self._connection.wrap_api_call(
  File "d:\dev\test\venv\lib\site-packages\undetected_playwright\_impl\_connection.py", line 495, in wrap_api_call
    return await cb()
  File "d:\dev\test\venv\lib\site-packages\undetected_playwright\_impl\_connection.py", line 101, in inner_send
    result = next(iter(done)).result()
undetected_playwright._impl._errors.Error: Cannot read properties of undefined (reading '_contextId')

**Comment by iceFbr** [comment]
same problem here.. something about dinamic frames. boring stuff and lots of ways to do the samething without interact with the frame

**Comment by aaronpeng2020** [comment]
Please give me some guidance, thank you very much

**Comment by iceFbr** [comment]
i belive you are trying to bypass arkose on twitter right? Arkose (over twitter or not) you can beat evaluating parent.postMessage(JSON.stringify({eventId:'challenge-complete',payload:{sessionToken:'" + captchaToken + "'}}),'*')"); 
(adapt / fix this code... i am over my phone and it sucks to code hahaha) 

It will work, just try it. 


If you debug the frame one of the .js has all possible postMessage...

**Comment by aaronpeng2020** [comment]
You misunderstood, I just want to manipulate the content within the iframe, like clicking a button.

The code is just an example.

**Comment by iceFbr** [comment]
I understood that, and I am saying you do not need to manipulate the content to do what you want!
